### ISSUE TITLE
Crashing app without Error

### ISSUE THREAD

**Issue by none283** [jhlothamer/save_and_load_demo#3]
![image](https://user-images.githubusercontent.com/61675554/209142977-42c27c3d-ebbe-4a8b-96cc-fb12c8807402.png)

I had GSHelper try to save `skill_bar` value, I tried to print `skill_bar` before save:
skill_bar = [bouncing_flower_skill:[Node:2093], Null, Null]
Delete the `skill_bar`, not try to save `skill_bar` will let everything ok, can save normal again

My Godot Version: 3.5.1 Stable

Crashed without error after clicked `OK` Button, and nothing saved in json file:
![image](https://user-images.githubusercontent.com/61675554/209143447-f8f89b33-61af-43f3-b13e-9c59c7e92e8f.png)
![image](https://user-images.githubusercontent.com/61675554/209143485-0aad1763-49d2-4556-bab5-13ec9a1238b2.png)
![image](https://user-images.githubusercontent.com/61675554/209143750-d6d5c83c-40e2-4118-8ab2-c5310b38ec71.png)

**Comment by none283** [comment]
Oh no sorry, the problem come from when i tried to change a property from `Node:2093` inside `skill_bar` and save the `skill_bar` array, it cause crash

![image](https://user-images.githubusercontent.com/61675554/209147166-c44d0c6a-50bf-4f3e-a6a3-6075c3287917.png)

#before
Node:2068.propertyinside = [[0, True], []]
[bouncing_flower_skill:[Node:2068], Null, Null]
#after
Node:2068.propertyinside = [[0, True, jump:[Node:2407]], [Foot_Position:[Position2D:2390], Player Skill Controller:[Node2D:2066]]]

then cause crash

Edit: I tried to set again value after used it, like:
Node:2068.propertyinside = [[0, True], []]
=> Node:2068.propertyinside = [[0, True, jump:[Node:2407]], [Foot_Position:[Position2D:2390], Player Skill Controller:[Node2D:2066]]]
=> Node:2068.propertyinside = [[0, True], []]

before save, and it save successful

**Comment by jhlothamer** [comment]
You can't save a node like this in the system.  It only handles basic types (arrays, dictionariess, string, int, float, etc.).  Not knowing exaclty how you set things up, this may be wrong, but I suggest adding the GameStateHelper node to the boucning_flower_skill node itself and add the properties you want to save to the Save Properties array.  

If that doesn't make sense or you think won't work, I'll need more info to give a better suggestion.  It might be easier to let me see your project.  If it's public, you can share the URL to it, or zip it up and attach it to a post on this issue.

**Comment by none283** [comment]
I tried to add GSHelper to boucing_flower_skill before but as you said, it can't save node like that so that not work, then i think i need to try other way, thank you for help
